(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#viewport'), ctx=canvas.getContext('2d'), wrap=$('#viewportWrap');
const state={project:newProject(),images:new Map(),selected:null,frame:1,playing:false,timer:null,view:{x:0,y:0,zoom:1},grid:true,bones:true,sockets:true,drag:null,history:[],future:[]};
function newProject(){return{format:'2d-rig-lab-web',version:1,name:'Untitled',fps:12,frames:32,animation:'Idle',direction:'Front',activeSkin:'Skin_Default',pieces:[],bones:[],sockets:[],skins:{Skin_Default:{replacements:{}}},weapons:[],equippedWeapon:'',animations:{}}}
const uid=p=>p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,6);
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),1800)}
function snapshot(){return JSON.stringify(state.project)}
function pushHistory(){state.history.push(snapshot());if(state.history.length>50)state.history.shift();state.future=[]}
function restore(s){state.project=JSON.parse(s);state.selected=null;hydrateImages();refreshAll()}
function undo(){if(!state.history.length)return;state.future.push(snapshot());restore(state.history.pop())}
function redo(){if(!state.future.length)return;state.history.push(snapshot());restore(state.future.pop())}
function animKey(){return state.project.animation+'|'+state.project.direction}
function anim(){const k=animKey();return state.project.animations[k]??=( {tracks:{}} )}
function track(id){return anim().tracks[id]??=( {} )}
function objectById(id){return [...state.project.pieces,...state.project.bones,...state.project.sockets].find(x=>x.id===id)}
function kindOf(id){if(state.project.pieces.some(x=>x.id===id))return'piece';if(state.project.bones.some(x=>x.id===id))return'bone';if(state.project.sockets.some(x=>x.id===id))return'socket';return''}
function boneById(id){return state.project.bones.find(x=>x.id===id)}
function socketByName(name){return state.project.sockets.find(x=>x.name===name)}
function deg(v){return v*Math.PI/180}
function lerp(a,b,t){return a+(b-a)*t}
function sample(id,frame){const tr=anim().tracks[id];if(!tr)return null;const ks=Object.keys(tr).map(Number).sort((a,b)=>a-b);if(!ks.length)return null;if(frame<=ks[0])return tr[ks[0]];if(frame>=ks.at(-1))return tr[ks.at(-1)];let a=ks[0],b=ks.at(-1);for(let i=0;i<ks.length-1;i++)if(frame>=ks[i]&&frame<=ks[i+1]){a=ks[i];b=ks[i+1];break}const t=(frame-a)/(b-a),A=tr[a],B=tr[b];return{x:lerp(A.x,B.x,t),y:lerp(A.y,B.y,t),r:lerp(A.r,B.r,t),sx:lerp(A.sx,B.sx,t),sy:lerp(A.sy,B.sy,t)}}
function local(o,frame=state.frame){const s=sample(o.id,frame);return s?{...o,...s}:o}
function compose(a,b){const c=Math.cos(deg(a.r)),s=Math.sin(deg(a.r));return{x:a.x+(b.x*a.sx*c-b.y*a.sy*s),y:a.y+(b.x*a.sx*s+b.y*a.sy*c),r:a.r+b.r,sx:a.sx*b.sx,sy:a.sy*b.sy}}
function boneWorld(id,frame=state.frame,seen=new Set()){if(!id||seen.has(id))return{x:0,y:0,r:0,sx:1,sy:1};seen.add(id);const b=boneById(id);if(!b)return{x:0,y:0,r:0,sx:1,sy:1};const l=local(b,frame);return b.parent?compose(boneWorld(b.parent,frame,seen),l):l}
function socketWorld(s,frame=state.frame){return compose(boneWorld(s.parent,frame),local(s,frame))}
function pieceWorld(p,frame=state.frame){let base={x:0,y:0,r:0,sx:1,sy:1};if(p.socket){const s=socketByName(p.socket);if(s)base=socketWorld(s,frame)}else if(p.parent)base=boneWorld(p.parent,frame);return compose(base,local(p,frame))}
function activeTexture(p){const rep=state.project.skins[state.project.activeSkin]?.replacements?.[p.id];return rep||p.texture}
function getImage(src){if(!src)return null;if(state.images.has(src))return state.images.get(src);const im=new Image();im.onload=()=>render();im.src=src;state.images.set(src,im);return im}
function hydrateImages(){state.images.clear();state.project.pieces.forEach(p=>getImage(p.texture));Object.values(state.project.skins).forEach(s=>Object.values(s.replacements||{}).forEach(getImage));state.project.weapons.forEach(w=>getImage(w.texture))}
function resize(){const dpr=Math.min(devicePixelRatio||1,2),r=wrap.getBoundingClientRect();canvas.width=Math.max(1,Math.floor(r.width*dpr));canvas.height=Math.max(1,Math.floor(r.height*dpr));canvas.style.width=r.width+'px';canvas.style.height=r.height+'px';ctx.setTransform(dpr,0,0,dpr,0,0);render()}
new ResizeObserver(resize).observe(wrap);
function screen(w){const r=wrap.getBoundingClientRect();return{x:r.width/2+state.view.x+w.x*state.view.zoom,y:r.height/2+state.view.y+w.y*state.view.zoom}}
function world(s){const r=wrap.getBoundingClientRect();return{x:(s.x-r.width/2-state.view.x)/state.view.zoom,y:(s.y-r.height/2-state.view.y)/state.view.zoom}}
function render(){const r=wrap.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);if(state.grid)drawGrid(r);[...state.project.pieces].sort((a,b)=>a.z-b.z).forEach(drawPiece);drawWeapon();if(state.bones)drawBones();if(state.sockets)drawSockets();$('#emptyState').classList.toggle('hidden',state.project.pieces.length>0);$('#zoomLabel').textContent=Math.round(state.view.zoom*100)+'%'}
function drawGrid(r){ctx.save();ctx.strokeStyle='rgba(255,255,255,.045)';ctx.lineWidth=1;let sp=32*state.view.zoom;if(sp<14)sp*=4;const ox=(r.width/2+state.view.x)%sp,oy=(r.height/2+state.view.y)%sp;for(let x=ox;x<r.width;x+=sp){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,r.height);ctx.stroke()}for(let y=oy;y<r.height;y+=sp){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(r.width,y);ctx.stroke()}ctx.restore()}
function drawPiece(p){const im=getImage(activeTexture(p));if(!im||!im.complete)return;const t=pieceWorld(p),q=screen(t);ctx.save();ctx.translate(q.x,q.y);ctx.rotate(deg(t.r));ctx.scale(t.sx*state.view.zoom,t.sy*state.view.zoom);ctx.globalAlpha=p.visible===false?.25:1;ctx.drawImage(im,-im.width*p.px,-im.height*p.py);if(state.selected===p.id){ctx.strokeStyle='#63d7ff';ctx.lineWidth=2/state.view.zoom;ctx.strokeRect(-im.width*p.px,-im.height*p.py,im.width,im.height);ctx.fillStyle='#ffd866';ctx.beginPath();ctx.arc(0,0,4/state.view.zoom,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawBones(){ctx.save();ctx.lineWidth=3;for(const b of state.project.bones){const t=boneWorld(b.id),a=screen(t),end=screen({x:t.x+Math.cos(deg(t.r))*b.length*t.sx,y:t.y+Math.sin(deg(t.r))*b.length*t.sx});ctx.strokeStyle=state.selected===b.id?'#ffe07a':'#ff9f5e';ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(end.x,end.y);ctx.stroke();ctx.beginPath();ctx.arc(a.x,a.y,5,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawSockets(){ctx.save();for(const s of state.project.sockets){const t=socketWorld(s),q=screen(t);ctx.strokeStyle=state.selected===s.id?'#fff':'#65e6a7';ctx.lineWidth=2;ctx.beginPath();ctx.arc(q.x,q.y,7,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(q.x-10,q.y);ctx.lineTo(q.x+10,q.y);ctx.moveTo(q.x,q.y-10);ctx.lineTo(q.x,q.y+10);ctx.stroke()}ctx.restore()}
function drawWeapon(){const w=state.project.weapons.find(x=>x.id===state.project.equippedWeapon);if(!w)return;const s=socketByName(w.socket);if(!s)return;const im=getImage(w.texture);if(!im||!im.complete)return;const t=compose(socketWorld(s),w),q=screen(t);ctx.save();ctx.translate(q.x,q.y);ctx.rotate(deg(t.r));ctx.scale(t.sx*state.view.zoom,t.sy*state.view.zoom);ctx.drawImage(im,-im.width*.5,-im.height*.5);ctx.restore()}
function hitPiece(pos){const w=world(pos);for(const p of [...state.project.pieces].sort((a,b)=>b.z-a.z)){const im=getImage(activeTexture(p));if(!im||!im.complete)continue;const t=pieceWorld(p),dx=w.x-t.x,dy=w.y-t.y,c=Math.cos(-deg(t.r)),s=Math.sin(-deg(t.r)),lx=(dx*c-dy*s)/t.sx,ly=(dx*s+dy*c)/t.sy;if(lx>=-im.width*p.px&&lx<=im.width*(1-p.px)&&ly>=-im.height*p.py&&ly<=im.height*(1-p.py))return p.id}return null}
function select(id){state.selected=id;refreshHierarchy();refreshInspector();refreshFrames();render()}
function refreshHierarchy(){const root=$('#hierarchy');root.innerHTML='';const groups=[['BONES','bone',state.project.bones],['PEÇAS','piece',state.project.pieces],['SOCKETS','socket',state.project.sockets]];for(const[g,k,arr]of groups){const title=document.createElement('div');title.className='tree-group';title.textContent=g;root.append(title);arr.forEach(o=>{const el=document.createElement('div');el.className=`tree-item ${k} ${state.selected===o.id?'selected':''}`;el.innerHTML='<i class="dot"></i><span></span>';el.querySelector('span').textContent=o.name;el.onclick=()=>select(o.id);root.append(el)})}}
function refreshInspector(){const o=objectById(state.selected),empty=$('#inspectorEmpty'),box=$('#inspector');empty.classList.toggle('hidden',!!o);box.classList.toggle('hidden',!o);if(!o)return;const k=kindOf(o.id),v=local(o);$('#propName').value=o.name;$('#propX').value=v.x;$('#propY').value=v.y;$('#propR').value=v.r;$('#propSX').value=v.sx;$('#propSY').value=v.sy;$$('.piece-only').forEach(e=>e.classList.toggle('hidden',k!=='piece'));if(k==='piece'){$('#propPX').value=o.px;$('#propPY').value=o.py;$('#propZ').value=o.z}const ps=$('#propParent');ps.innerHTML='<option value="">(nenhum)</option>'+state.project.bones.filter(b=>b.id!==o.id).map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('');ps.value=k==='bone'?o.parent||'':o.parent||'';const ss=$('#propSocket');ss.innerHTML='<option value="">(nenhum)</option>'+state.project.sockets.map(s=>`<option>${esc(s.name)}</option>`).join('');if(k==='piece')ss.value=o.socket||''}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function updateSelected(){const o=objectById(state.selected);if(!o)return;pushHistory();o.name=$('#propName').value;o.x=+$(`#propX`).value;o.y=+$(`#propY`).value;o.r=+$(`#propR`).value;o.sx=+$(`#propSX`).value;o.sy=+$(`#propSY`).value;o.parent=$('#propParent').value;if(kindOf(o.id)==='piece'){o.px=+$(`#propPX`).value;o.py=+$(`#propPY`).value;o.z=+$(`#propZ`).value;o.socket=$('#propSocket').value}refreshAll()}
function refreshFrames(){const row=$('#frames');row.innerHTML='';const tr=state.selected?anim().tracks[state.selected]:null;for(let i=1;i<=state.project.frames;i++){const b=document.createElement('button');b.className='frame '+(i===state.frame?'active ':'')+(tr?.[i]?'key':'');b.textContent=i;b.onclick=()=>setFrame(i);row.append(b)}$('#frameReadout').textContent=`${state.frame} / ${state.project.frames}`}
function setFrame(n){state.frame=Math.max(1,Math.min(state.project.frames,n));refreshInspector();refreshFrames();render()}
function addKey(){const o=objectById(state.selected);if(!o)return toast('Selecione uma peça ou bone');pushHistory();const l=local(o);track(o.id)[state.frame]={x:l.x,y:l.y,r:l.r,sx:l.sx,sy:l.sy};refreshFrames();toast('Keyframe adicionado')}
function refreshAssets(){const skins=$('#skinSelect');skins.innerHTML=Object.keys(state.project.skins).map(n=>`<option>${esc(n)}</option>`).join('');skins.value=state.project.activeSkin;const weapons=$('#weaponSelect');weapons.innerHTML='<option value="">(nenhuma)</option>'+state.project.weapons.map(w=>`<option value="${w.id}">${esc(w.name)}</option>`).join('');weapons.value=state.project.equippedWeapon}
function refreshAll(){refreshHierarchy();refreshInspector();refreshFrames();refreshAssets();$('#animSelect').value=state.project.animation;$('#dirSelect').value=state.project.direction;$('#fps').value=state.project.fps;render()}
function fileData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
async function importPNGs(files){pushHistory();for(const f of files){const data=await fileData(f),im=new Image();im.src=data;await im.decode().catch(()=>{});const p={id:uid('piece'),name:f.name.replace(/\.png$/i,''),texture:data,x:0,y:0,r:0,sx:1,sy:1,px:.5,py:.5,z:state.project.pieces.length,parent:'',socket:'',visible:true};state.project.pieces.push(p);getImage(data);state.selected=p.id}refreshAll();fitView();toast(`${files.length} PNG(s) importado(s)`) }
function addBone(){pushHistory();const b={id:uid('bone'),name:'Bone_'+(state.project.bones.length+1),x:0,y:0,r:0,sx:1,sy:1,length:60,parent:''};state.project.bones.push(b);select(b.id)}
function addSocket(){pushHistory();const s={id:uid('socket'),name:state.project.sockets.length?'Socket_'+(state.project.sockets.length+1):'RightHand',x:0,y:0,r:0,sx:1,sy:1,parent:kindOf(state.selected)==='bone'?state.selected:''};state.project.sockets.push(s);select(s.id)}
function delSelected(){if(!state.selected)return;pushHistory();for(const key of['pieces','bones','sockets'])state.project[key]=state.project[key].filter(x=>x.id!==state.selected);state.selected=null;refreshAll()}
function fitView(){if(!state.project.pieces.length){state.view={x:0,y:0,zoom:1};return render()}let pts=state.project.pieces.map(pieceWorld),minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxY=Math.max(...pts.map(p=>p.y)),rw=Math.max(200,maxX-minX+300),rh=Math.max(200,maxY-minY+300),r=wrap.getBoundingClientRect();state.view.zoom=Math.max(.15,Math.min(2.2,Math.min(r.width/rw,r.height/rh)));state.view.x=-(minX+maxX)/2*state.view.zoom;state.view.y=-(minY+maxY)/2*state.view.zoom;render()}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function saveProject(){download('2d-rig-lab-project.json',JSON.stringify(state.project,null,2));toast('Projeto salvo')}
function exportClean(){const p=structuredClone(state.project);download('character.json',JSON.stringify(p,null,2));toast('JSON exportado')}
function loadProject(file){const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(!p.pieces||!p.bones)throw 0;pushHistory();state.project=p;state.frame=1;state.selected=null;hydrateImages();refreshAll();fitView();toast('Projeto aberto')}catch{toast('JSON inválido')}};r.readAsText(file)}
function play(){state.playing=!state.playing;$('#play').textContent=state.playing?'⏸':'▶';clearInterval(state.timer);if(state.playing)state.timer=setInterval(()=>setFrame(state.frame>=state.project.frames?1:state.frame+1),1000/state.project.fps)}
function stop(){state.playing=false;clearInterval(state.timer);$('#play').textContent='▶';setFrame(1)}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);const rect=canvas.getBoundingClientRect(),pos={x:e.clientX-rect.left,y:e.clientY-rect.top},hit=hitPiece(pos);if(hit){select(hit);const o=objectById(hit);state.drag={mode:'piece',id:hit,start:pos,ox:o.x,oy:o.y};pushHistory()}else{state.drag={mode:'pan',start:pos,ox:state.view.x,oy:state.view.y};select(null)}});
canvas.addEventListener('pointermove',e=>{if(!state.drag)return;const rect=canvas.getBoundingClientRect(),p={x:e.clientX-rect.left,y:e.clientY-rect.top},dx=p.x-state.drag.start.x,dy=p.y-state.drag.start.y;if(state.drag.mode==='pan'){state.view.x=state.drag.ox+dx;state.view.y=state.drag.oy+dy}else{const o=objectById(state.drag.id);o.x=state.drag.ox+dx/state.view.zoom;o.y=state.drag.oy+dy/state.view.zoom;refreshInspector()}render()});
canvas.addEventListener('pointerup',()=>state.drag=null);canvas.addEventListener('pointercancel',()=>state.drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();const f=e.deltaY<0?1.1:.9;state.view.zoom=Math.max(.1,Math.min(6,state.view.zoom*f));render()},{passive:false});
let pinch=null;canvas.addEventListener('touchstart',e=>{if(e.touches.length===2){const[a,b]=e.touches;pinch={d:Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY),z:state.view.zoom}}},{passive:true});canvas.addEventListener('touchmove',e=>{if(e.touches.length===2&&pinch){const[a,b]=e.touches,d=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);state.view.zoom=Math.max(.1,Math.min(6,pinch.z*d/pinch.d));render()}},{passive:true});canvas.addEventListener('touchend',()=>pinch=null);
$('#pngInput').onchange=e=>importPNGs([...e.target.files]);$('#projectInput').onchange=e=>e.target.files[0]&&loadProject(e.target.files[0]);$('#addBone').onclick=addBone;$('#addSocket').onclick=addSocket;$('#fitView').onclick=fitView;$('#toggleGrid').onclick=e=>{state.grid=!state.grid;e.currentTarget.classList.toggle('active',state.grid);render()};$('#toggleBones').onclick=e=>{state.bones=!state.bones;e.currentTarget.classList.toggle('active',state.bones);render()};$('#toggleSockets').onclick=e=>{state.sockets=!state.sockets;e.currentTarget.classList.toggle('active',state.sockets);render()};$('#deleteSelected').onclick=delSelected;$('#prevFrame').onclick=()=>setFrame(state.frame-1);$('#nextFrame').onclick=()=>setFrame(state.frame+1);$('#play').onclick=play;$('#stop').onclick=stop;$('#addKey').onclick=addKey;$('#fps').onchange=e=>{state.project.fps=Math.max(1,+e.target.value||12);if(state.playing){stop();play()}};$('#animSelect').onchange=e=>{state.project.animation=e.target.value;setFrame(1)};$('#dirSelect').onchange=e=>{state.project.direction=e.target.value;setFrame(1)};
['propName','propX','propY','propR','propSX','propSY','propPX','propPY','propZ','propParent','propSocket'].forEach(id=>$('#'+id).addEventListener('change',updateSelected));
$('#skinSelect').onchange=e=>{state.project.activeSkin=e.target.value;render()};$('#newSkin').onclick=()=>{const n=prompt('Nome da nova skin:','Skin_Red');if(!n||state.project.skins[n])return;pushHistory();state.project.skins[n]={replacements:{}};state.project.activeSkin=n;refreshAssets();render()};$('#skinTextureInput').onchange=async e=>{const p=objectById(state.selected);if(kindOf(state.selected)!=='piece')return toast('Selecione uma peça');const f=e.target.files[0];if(!f)return;pushHistory();state.project.skins[state.project.activeSkin].replacements[p.id]=await fileData(f);hydrateImages();render();toast('PNG da skin atualizado')};
$('#weaponInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;const socket=state.project.sockets[0]?.name||'RightHand';pushHistory();const w={id:uid('weapon'),name:f.name.replace(/\.png$/i,''),texture:await fileData(f),socket,x:0,y:0,r:0,sx:1,sy:1};state.project.weapons.push(w);state.project.equippedWeapon=w.id;hydrateImages();refreshAssets();render()};$('#equipWeapon').onclick=()=>{state.project.equippedWeapon=$('#weaponSelect').value;render()};
$$('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='new'){if(confirm('Criar projeto novo?')){pushHistory();state.project=newProject();state.selected=null;state.frame=1;hydrateImages();refreshAll()}}else if(a==='open')$('#projectInput').click();else if(a==='save')saveProject();else if(a==='export')exportClean();else if(a==='undo')undo();else if(a==='redo')redo()});
$$('[data-mobile]').forEach(b=>b.onclick=()=>{$$('[data-mobile]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.body.classList.remove('mobile-rig','mobile-timeline','mobile-inspector');if(b.dataset.mobile!=='viewport')document.body.classList.add('mobile-'+b.dataset.mobile);setTimeout(resize,30)});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveProject()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if(e.code==='Space'&&!['INPUT','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();play()}else if(e.key==='Delete')delSelected()});
refreshAll();resize();
})();
