import { SceneEngine, THREE } from './scene-engine.js';
import { createPrimitive, deepCloneObject, MATERIAL_PRESETS, applyMaterial, materialFromObject } from './object-factory.js';
import { createTemplate, createWheel, availableMounts, snapToMount } from './templates.js';
import { MirrorSystem } from './mirror-system.js';
import { MeshEditor } from './mesh-editor.js';
import { CommandHistory, captureTransform, applyTransform } from './history.js';
import { exportGLB, exportGLTF, exportOBJ, saveProject, loadProject } from './project-export.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const canvas=$('#modelerCanvas'),wrap=$('.viewport-panel'),engine=new SceneEngine(canvas,wrap),mirror=new MirrorSystem();
let selected=[],clipboard=null,transformBefore=null,transformDragging=false,lastTransformMode='translate',projectName='Meu Projeto 3D',suggestionAction=null;
const history=new CommandHistory(80,s=>{$('#historyStatus').textContent=`${s.label} · Undo ${s.undo} · Redo ${s.redo}`});
const meshEditor=new MeshEditor(engine,{onCommit:onGeometryCommit,getMirror:()=>({axes:mirror.axesFor(active()),clipping:$('#mirrorClipping').checked})});

const editable=o=>o&&o!==engine.root&&!o.userData?.helper&&!o.userData?.isMount;
const active=()=>selected[0]||null;
function selectableFrom(o){let cur=o;while(cur&&cur!==engine.root){if(editable(cur))return cur;cur=cur.parent}return null}
function allEditable(){const list=[];engine.root.traverse(o=>{if(editable(o))list.push(o)});return list}
function meshCount(){let n=0;engine.root.traverse(o=>{if(o.isMesh&&!o.userData?.helper&&!o.userData?.isMount)n++});return n}

function select(obj,add=false){
 if(meshEditor.active&&obj!==meshEditor.mesh)exitVertexMode();if(!obj){selected=[];engine.detach();updateSelectionUI();renderOutliner();return}
 if(!editable(obj)&&obj!==engine.root)return;if(add){const i=selected.indexOf(obj);if(i>=0)selected.splice(i,1);else selected.unshift(obj)}else selected=[obj];
 if(!meshEditor.active)engine.attach(active());updateSelectionUI();renderOutliner();syncMirrorUI();
}
function updateSelectionUI(){const o=active(),disabled=!o;$('#selectionType').textContent=o?(o.isMesh?'Mesh':o.type):'Nada selecionado';$('#selectionStatus').textContent=o?`${selected.length>1?selected.length+' selecionados · ':''}${o.name}`:'Nenhum objeto selecionado';const ids=['objectName','posX','posY','posZ','rotX','rotY','rotZ','scaleX','scaleY','scaleZ'];ids.forEach(id=>$('#'+id).disabled=disabled);if(!o)return;$('#objectName').value=o.name;$('#posX').value=f(o.position.x);$('#posY').value=f(o.position.y);$('#posZ').value=f(o.position.z);$('#rotX').value=f(THREE.MathUtils.radToDeg(o.rotation.x),1);$('#rotY').value=f(THREE.MathUtils.radToDeg(o.rotation.y),1);$('#rotZ').value=f(THREE.MathUtils.radToDeg(o.rotation.z),1);$('#scaleX').value=f(o.scale.x);$('#scaleY').value=f(o.scale.y);$('#scaleZ').value=f(o.scale.z);const m=materialFromObject(o);if(m){$('#matColor').value='#'+m.color.getHexString();$('#matEmissive').value='#'+(m.emissive?.getHexString?.()||'000000');$('#matMetallic').value=m.metalness??0;$('#matRoughness').value=m.roughness??.5;$('#matOpacity').value=m.opacity??1;syncMaterialOutputs()}}
function f(v,d=2){return Number(v||0).toFixed(d)}
function renderOutliner(){const box=$('#outliner');box.innerHTML='';let count=0;function row(obj,depth){if(obj.userData?.helper||obj.userData?.isMount)return;count++;const b=document.createElement('button');b.className='outliner-row'+(selected.includes(obj)?' selected':'');b.style.paddingLeft=(7+depth*13)+'px';b.innerHTML=`<span class="type">${obj.isMesh?'◆':obj.isGroup?'▾':'◇'}</span><span>${escapeHtml(obj.name||obj.type)}</span>`;b.onclick=e=>select(obj,e.shiftKey);box.appendChild(b);for(const c of obj.children)row(c,depth+1)}for(const c of engine.root.children)row(c,0);if(!count)box.innerHTML='<div class="outliner-empty">Cena vazia</div>';$('#objectCount').textContent=`${count} objeto${count===1?'':'s'}`;$('#addWheelBtn').classList.toggle('hidden',!findCar())}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}

function addObject(obj,{selectIt=true,record=true}={}){engine.root.add(obj);if(record)history.push({label:'Adicionar '+obj.name,undo:()=>{obj.parent?.remove(obj);if(selected.includes(obj))select(null)},redo:()=>{engine.root.add(obj);renderOutliner()}});renderOutliner();if(selectIt)select(obj);return obj}
function removeSelected(){if(!selected.length)return;exitVertexMode();const items=selected.map(o=>({o,parent:o.parent,index:o.parent?.children.indexOf(o)}));items.forEach(({o})=>{mirror.clear(o,false);o.parent?.remove(o)});selected=[];engine.detach();history.push({label:'Excluir objeto',undo:()=>{for(const it of items){it.parent?.add(it.o)}renderOutliner()},redo:()=>{for(const it of items)it.o.parent?.remove(it.o);select(null);renderOutliner()}});updateSelectionUI();renderOutliner()}
function duplicate(instance=false){const o=active();if(!o)return;const c=deepCloneObject(o,{instance});c.userData.mountUuid=null;c.userData.mountName=null;c.position.x+=.45;(o.parent||engine.root).add(c);history.push({label:instance?'Criar instância':'Duplicar objeto',undo:()=>c.parent?.remove(c),redo:()=>{(o.parent||engine.root).add(c);renderOutliner()}});renderOutliner();select(c);trySmartSnap(c)}
function groupSelected(){if(selected.length<2)return;exitVertexMode();const objs=[...selected],parents=objs.map(o=>o.parent),g=new THREE.Group();g.name='Grupo';g.userData.editable=true;engine.root.add(g);objs.forEach(o=>g.attach(o));history.push({label:'Agrupar objetos',undo:()=>{objs.forEach((o,i)=>parents[i]?.attach(o));g.parent?.remove(g);renderOutliner()},redo:()=>{engine.root.add(g);objs.forEach(o=>g.attach(o));renderOutliner()}});renderOutliner();select(g)}

$$('[data-primitive]').forEach(b=>b.onclick=()=>{const o=createPrimitive(b.dataset.primitive);o.position.y=b.dataset.primitive==='plane'?0:1;addObject(o)});
$$('[data-transform]').forEach(b=>b.onclick=()=>{if(meshEditor.active)exitVertexMode();lastTransformMode=b.dataset.transform;engine.setTransformMode(lastTransformMode);$$('[data-transform]').forEach(x=>x.classList.toggle('active',x===b));if(active())engine.attach(active())});
$('#duplicateBtn').onclick=()=>duplicate(false);$('#instanceBtn').onclick=()=>duplicate(true);$('#deleteBtn').onclick=removeSelected;$('#groupBtn').onclick=groupSelected;

engine.onTransform({
 dragging:v=>{transformDragging=v},
 start:()=>{if(meshEditor.active){meshEditor.transformStart();return}const o=active();if(o)transformBefore=captureTransform(o)},
 change:()=>{if(meshEditor.active){meshEditor.transformChange();return}const o=active();if(o){mirror.sync(o);updateSelectionUI()}},
 end:()=>{if(meshEditor.active){meshEditor.transformEnd();return}const o=active();if(!o||!transformBefore)return;const before=transformBefore,after=captureTransform(o);transformBefore=null;if(!sameTransform(before,after))history.push({label:'Transformar '+o.name,undo:()=>{applyTransform(o,before);mirror.sync(o);updateSelectionUI()},redo:()=>{applyTransform(o,after);mirror.sync(o);updateSelectionUI()}});trySmartSnap(o);updateSelectionUI()}
});
function sameTransform(a,b){return a.position.distanceToSquared(b.position)<1e-12&&a.scale.distanceToSquared(b.scale)<1e-12&&Math.abs(a.quaternion.dot(b.quaternion))>.999999}

canvas.addEventListener('pointerdown',e=>{if(engine.transform.axis)return;if(meshEditor.active){meshEditor.pointerSelect(e);return}const ray=engine.screenRay(e.clientX,e.clientY),hits=ray.intersectObjects(engine.root.children,true).filter(h=>!h.object.userData?.helper&&!h.object.userData?.isMount);const obj=hits.length?selectableFrom(hits[0].object):null;select(obj,e.shiftKey)});

$$('[data-view]').forEach(b=>b.onclick=()=>{$$('[data-view]').forEach(x=>x.classList.toggle('active',x===b));engine.frameObjects(selected.length?selected:[engine.root],b.dataset.view)});
$('#orthoBtn').onclick=()=>{engine.setOrtho(!engine.isOrtho);$('#orthoBtn').textContent=engine.isOrtho?'Ortográfica':'Perspectiva';if(meshEditor.active){const mesh=meshEditor.mesh;meshEditor.exit();meshEditor.enter(mesh)}else if(active())engine.attach(active())};

let propBefore=null;$$('#posX,#posY,#posZ,#rotX,#rotY,#rotZ,#scaleX,#scaleY,#scaleZ').forEach(inp=>{inp.addEventListener('focus',()=>{if(active())propBefore=captureTransform(active())});inp.addEventListener('change',()=>{const o=active();if(!o)return;const before=propBefore||captureTransform(o);o.position.set(num('#posX',o.position.x),num('#posY',o.position.y),num('#posZ',o.position.z));o.rotation.set(THREE.MathUtils.degToRad(num('#rotX',THREE.MathUtils.radToDeg(o.rotation.x))),THREE.MathUtils.degToRad(num('#rotY',THREE.MathUtils.radToDeg(o.rotation.y))),THREE.MathUtils.degToRad(num('#rotZ',THREE.MathUtils.radToDeg(o.rotation.z))));o.scale.set(num('#scaleX',o.scale.x),num('#scaleY',o.scale.y),num('#scaleZ',o.scale.z));const after=captureTransform(o);mirror.sync(o);history.push({label:'Editar propriedades',undo:()=>{applyTransform(o,before);mirror.sync(o);updateSelectionUI()},redo:()=>{applyTransform(o,after);mirror.sync(o);updateSelectionUI()}});propBefore=null;updateSelectionUI()})});
function num(sel,fallback){const v=parseFloat($(sel).value);return Number.isFinite(v)?v:fallback}
$('#objectName').addEventListener('change',()=>{const o=active();if(!o)return;const before=o.name,after=$('#objectName').value.trim()||before;o.name=after;history.push({label:'Renomear objeto',undo:()=>{o.name=before;renderOutliner();updateSelectionUI()},redo:()=>{o.name=after;renderOutliner();updateSelectionUI()}});renderOutliner()});

function enterVertexMode(){const o=active();if(!o)return;if(!meshEditor.enter(o)){alert('Selecione um objeto com geometria editável.');return}$('#objectModeBtn').classList.remove('active');$('#vertexModeBtn').classList.add('active');$('#modeStatus').textContent='MODO VÉRTICE';updateSelectionUI()}
function exitVertexMode(){if(!meshEditor.active)return;meshEditor.exit();$('#objectModeBtn').classList.add('active');$('#vertexModeBtn').classList.remove('active');$('#modeStatus').textContent='MODO OBJETO';engine.setTransformMode(lastTransformMode);if(active())engine.attach(active())}
$('#vertexModeBtn').onclick=enterVertexMode;$('#objectModeBtn').onclick=exitVertexMode;$('#mergeVerticesBtn').onclick=()=>meshEditor.mergeSelected();$('#subdivideBtn').onclick=()=>{if(!meshEditor.active)enterVertexMode();if(meshEditor.active)meshEditor.subdivide()};
function onGeometryCommit(before,after,mesh,swap=false){mirror.sync(selectableFrom(mesh)||mesh);if(swap){history.push({label:'Subdivide',undo:()=>{mesh.geometry=before.clone();refreshMeshEditor(mesh)},redo:()=>{mesh.geometry=after.clone();refreshMeshEditor(mesh)}})}else{history.push({label:'Editar vértices',undo:()=>{setPositions(mesh,before);refreshMeshEditor(mesh)},redo:()=>{setPositions(mesh,after);refreshMeshEditor(mesh)}})}}
function setPositions(mesh,array){const p=mesh.geometry.getAttribute('position');if(p&&p.array.length===array.length){p.array.set(array);p.needsUpdate=true;mesh.geometry.computeVertexNormals();mesh.geometry.computeBoundingBox();mesh.geometry.computeBoundingSphere()}}
function refreshMeshEditor(mesh){mirror.sync(selectableFrom(mesh)||mesh);if(meshEditor.active){meshEditor.exit();meshEditor.enter(mesh)}}

function currentMirrorAxes(){return[['x','#mirrorX'],['y','#mirrorY'],['z','#mirrorZ']].filter(([,s])=>$(s).checked).map(([a])=>a)}
function syncMirrorUI(){const o=active(),axes=mirror.axesFor(o);$('#mirrorX').checked=axes.includes('x');$('#mirrorY').checked=axes.includes('y');$('#mirrorZ').checked=axes.includes('z')}
function updateMirror(){const o=active();if(!o)return;mirror.setOptions({clipping:$('#mirrorClipping').checked,merge:$('#mirrorMerge').checked});const old=mirror.axesFor(o),next=currentMirrorAxes();const removing=old.some(a=>!next.includes(a));if(removing&&mirror.has(o))mirror.apply(o);if(next.length)mirror.setAxes(o,next);renderOutliner()}
['#mirrorX','#mirrorY','#mirrorZ'].forEach(s=>$(s).onchange=updateMirror);$('#mirrorClipping').onchange=()=>mirror.setOptions({clipping:$('#mirrorClipping').checked});$('#mirrorMerge').onchange=()=>mirror.setOptions({merge:$('#mirrorMerge').checked});$('#applyMirrorBtn').onclick=()=>{const o=active();if(!o)return;const made=mirror.apply(o);['#mirrorX','#mirrorY','#mirrorZ'].forEach(s=>$(s).checked=false);renderOutliner();if(made.length)showSuggestion(`Mirror aplicado: ${made.length} parte${made.length===1?'':'s'} agora é independente.`,null)};

$('#createTemplateBtn').onclick=()=>{const type=$('#templateSelect').value;if(type==='object'){const o=createPrimitive('cube','Objeto_Base');o.position.y=1;addObject(o);engine.frameObjects([o]);return}const t=createTemplate(type);engine.root.add(t);history.push({label:'Criar base '+t.name,undo:()=>t.parent?.remove(t),redo:()=>{engine.root.add(t);renderOutliner()}});renderOutliner();select(t);engine.frameObjects([t]);if(type==='car')showSuggestion('Base de carro criada com 4 pontos inteligentes para rodas. Quer adicionar a primeira roda?',()=>addWheel())};
$('#addWheelBtn').onclick=()=>addWheel();
function findCar(){let car=null;engine.root.traverse(o=>{if(!car&&o.userData?.template==='car')car=o});return car}
function addWheel(){const car=findCar();if(!car)return;const mounts=availableMounts(car,'wheel');if(!mounts.length){showSuggestion('Todos os pontos de roda já estão ocupados.',null);return}const wheel=createWheel();car.add(wheel);snapToMount(wheel,mounts[0]);history.push({label:'Adicionar roda',undo:()=>wheel.parent?.remove(wheel),redo:()=>car.add(wheel)});renderOutliner();select(wheel);const remain=availableMounts(car,'wheel');if(remain.length)showSuggestion(`Roda encaixada. Duplicar automaticamente para os outros ${remain.length} pontos de montagem?`,()=>fillRemainingWheels(wheel,car))}
function fillRemainingWheels(source,car){const made=[];for(const m of availableMounts(car,'wheel')){const w=deepCloneObject(source,{instance:false});w.userData.mountUuid=null;w.userData.mountName=null;car.add(w);snapToMount(w,m);made.push(w)}if(made.length)history.push({label:'Completar rodas',undo:()=>made.forEach(o=>o.parent?.remove(o)),redo:()=>made.forEach(o=>car.add(o))});renderOutliner();hideSuggestion()}
function trySmartSnap(o){if(!$('#smartSnap').checked||!o?.userData?.snapType)return;const candidates=[];engine.root.traverse(x=>{if(x.userData?.isMount&&x.userData.mountType===o.userData.snapType&&!x.userData.occupied)candidates.push(x)});if(!candidates.length)return;const op=o.getWorldPosition(new THREE.Vector3());let best=null,dist=Infinity;for(const m of candidates){const d=op.distanceTo(m.getWorldPosition(new THREE.Vector3()));if(d<dist){dist=d;best=m}}if(best&&dist<1.15){snapToMount(o,best);mirror.sync(o);updateSelectionUI();const car=findCar(),remain=car?availableMounts(car,'wheel'):[];if(o.userData.snapType==='wheel'&&remain.length)showSuggestion(`Smart Snap encaixou a roda. Duplicar para os ${remain.length} pontos restantes?`,()=>fillRemainingWheels(o,car))}}

function showSuggestion(text,action){$('#suggestionText').textContent=text;suggestionAction=action;$('#suggestionAccept').classList.toggle('hidden',!action);$('#smartSuggestion').classList.remove('hidden')}
function hideSuggestion(){$('#smartSuggestion').classList.add('hidden');suggestionAction=null}
$('#suggestionAccept').onclick=()=>suggestionAction?.();$('#suggestionClose').onclick=hideSuggestion;

function syncMaterialOutputs(){$('#metallicOut').value=(+$('#matMetallic').value).toFixed(2);$('#roughnessOut').value=(+$('#matRoughness').value).toFixed(2);$('#opacityOut').value=(+$('#matOpacity').value).toFixed(2)}
['#matMetallic','#matRoughness','#matOpacity'].forEach(s=>$(s).oninput=syncMaterialOutputs);syncMaterialOutputs();
$('#materialPreset').onchange=()=>{const p=MATERIAL_PRESETS[$('#materialPreset').value];if(!p)return;$('#matColor').value=p.color;$('#matMetallic').value=p.metalness;$('#matRoughness').value=p.roughness;$('#matOpacity').value=p.opacity;syncMaterialOutputs()};
let pendingTexture=null;$('#textureInput').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;const data=await fileToDataURL(file);pendingTexture=await new THREE.TextureLoader().loadAsync(data);pendingTexture.colorSpace=THREE.SRGBColorSpace;pendingTexture.flipY=false;showSuggestion('Textura carregada. Clique em “Aplicar material” para usar no objeto selecionado.',null)};
$('#applyMaterialBtn').onclick=()=>{const o=active();if(!o)return;const before=captureMaterials(o),settings={color:$('#matColor').value,emissive:$('#matEmissive').value,metalness:+$('#matMetallic').value,roughness:+$('#matRoughness').value,opacity:+$('#matOpacity').value};if(pendingTexture)settings.map=pendingTexture;applyMaterial(o,settings);const after=captureMaterials(o);mirror.sync(o);history.push({label:'Alterar material',undo:()=>restoreMaterials(before),redo:()=>restoreMaterials(after)});pendingTexture=null};
function captureMaterials(o){const arr=[];o.traverse(m=>{if(m.isMesh&&m.material)arr.push({mesh:m,material:Array.isArray(m.material)?m.material.map(x=>x.clone()):m.material.clone()})});return arr}
function restoreMaterials(snapshot){snapshot.forEach(x=>x.mesh.material=Array.isArray(x.material)?x.material.map(m=>m.clone()):x.material.clone());if(active())mirror.sync(active())}
function fileToDataURL(file){return new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file)})}

$('#projectName').oninput=e=>projectName=e.target.value||'Meu Projeto 3D';$('#saveProjectBtn').onclick=()=>saveProject(engine.root,projectName);$('#exportGlbBtn').onclick=()=>exportGLB(engine.root,projectName).catch(showError);$('#exportGltfBtn').onclick=()=>exportGLTF(engine.root,projectName).catch(showError);$('#exportObjBtn').onclick=()=>{try{exportOBJ(engine.root,projectName)}catch(e){showError(e)}};
$('#openProjectInput').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const data=await loadProject(file);newProject(false);for(const c of [...data.object.children])engine.root.add(c);projectName=data.name;$('#projectName').value=projectName;renderOutliner();engine.frameObjects([engine.root]);history.clear()}catch(err){showError(err)}e.target.value=''};
$('#newProjectBtn').onclick=()=>newProject(true);
function newProject(confirmFirst=true){if(confirmFirst&&engine.root.children.length&&!confirm('Criar um projeto novo? A cena atual será limpa.'))return false;exitVertexMode();mirror.removeAll();for(const c of [...engine.root.children])engine.root.remove(c);selected=[];engine.detach();history.clear();renderOutliner();updateSelectionUI();projectName='Meu Projeto 3D';$('#projectName').value=projectName;hideSuggestion();return true}
function showError(e){console.error(e);alert('Não foi possível concluir esta operação.')}

function copy(){if(active())clipboard=deepCloneObject(active(),{instance:false})}
function paste(){if(!clipboard)return;const c=deepCloneObject(clipboard,{instance:false});c.name=clipboard.name+' Colado';c.position.x+=.35;addObject(c)}
window.addEventListener('keydown',e=>{const tag=document.activeElement?.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag)&&!(e.ctrlKey||e.metaKey))return;const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='c'){e.preventDefault();copy()}else if(mod&&e.key.toLowerCase()==='v'){e.preventDefault();paste()}else if(mod&&e.key.toLowerCase()==='z'&&!e.shiftKey){e.preventDefault();history.undo();renderOutliner();updateSelectionUI()}else if(mod&&e.key.toLowerCase()==='z'&&e.shiftKey){e.preventDefault();history.redo();renderOutliner();updateSelectionUI()}else if(e.key==='Delete'||e.key==='Backspace'&&tag!=='INPUT'){e.preventDefault();removeSelected()}else if(e.key.toLowerCase()==='g'&&!mod){lastTransformMode='translate';engine.setTransformMode('translate')}else if(e.key.toLowerCase()==='r'&&!mod){lastTransformMode='rotate';engine.setTransformMode('rotate')}else if(e.key.toLowerCase()==='s'&&!mod){lastTransformMode='scale';engine.setTransformMode('scale')}});

function onGeometryReady(){renderOutliner();updateSelectionUI()}
function sameArray(a,b){if(!a||!b||a.length!==b.length)return false;for(let i=0;i<a.length;i++)if(Math.abs(a[i]-b[i])>1e-7)return false;return true}
function onGeometryCommit(before,after,mesh,swap=false){if(!swap&&sameArray(before,after))return;mirror.sync(selectableFrom(mesh)||mesh);if(swap){history.push({label:'Subdivide',undo:()=>{mesh.geometry=before.clone();refreshMeshEditor(mesh)},redo:()=>{mesh.geometry=after.clone();refreshMeshEditor(mesh)}})}else history.push({label:'Editar vértices',undo:()=>{setPositions(mesh,before);refreshMeshEditor(mesh)},redo:()=>{setPositions(mesh,after);refreshMeshEditor(mesh)}})}

renderOutliner();updateSelectionUI();engine.frameObjects([engine.root]);
showSuggestion('Editor 3D pronto. Comece com uma forma básica ou escolha uma Base de Modelagem.',null);
