import * as THREE from 'three';
import { MeshSelection } from './selection/mesh-selection.js';
import { editableGeometry,refreshGeometry,subdivisionOnce } from './mesh/geometry-utils.js';
import { extrudeFaces } from './mesh/extrude.js';
import { insetFaces } from './mesh/inset.js';
import { loopCut } from './mesh/loop-cut.js';
import { bevelEdges } from './mesh/bevel.js';
import { knifeFace,nearestPointOnFaceEdges } from './mesh/knife.js';
import { SubdivisionModifier } from './features/subdivision/modifier.js';

export class MeshEditor{
 constructor(engine,{onCommit=()=>{},getMirror=()=>({axes:[],clipping:false}),onSelectionChange=()=>{}}={}){
  this.engine=engine;this.onCommit=onCommit;this.getMirror=getMirror;this.onSelectionChange=onSelectionChange;this.mesh=null;this.proxy=null;this.dragBefore=null;this.proxyStart=null;this.proportional=false;this.proportionalRadius=.75;this.knifeState=null;this.knifePreview=null;this.subdivision=new SubdivisionModifier();
  this.selection=new MeshSelection(engine,s=>{this._updateProxy();onSelectionChange({active:this.active,...s});this._syncModeStatus(s)});
  queueMicrotask(()=>this.bindUI());
 }
 get active(){return!!this.mesh}
 get mode(){return this.selection.mode}
 get selected(){return this.selection.selectedVertexIndices()}
 bindUI(){
  const sec=document.querySelector('#modelingSec');if(!sec||sec.dataset.meshV4)return;sec.dataset.meshV4='1';
  const advanced=sec.querySelector('.advanced-grid');if(advanced)advanced.innerHTML=`<button data-mesh-mode="edge" title="Seleção de arestas · 2">Aresta</button><button data-mesh-mode="face" title="Seleção de faces · 3">Face</button><button id="extrudeMeshBtn" title="Extrudar faces · E">Extrude</button><button id="insetMeshBtn" title="Inset · I">Inset</button><button id="bevelMeshBtn" title="Bevel · B">Bevel</button><button id="loopCutMeshBtn" title="Loop Cut · Ctrl+R">Loop Cut</button><button id="knifeMeshBtn" title="Knife · K">Knife</button><button id="propEditBtn" title="Proportional Editing · O">Proporcional</button>`;
  const segmented=sec.querySelector('.segmented');const v=segmented?.querySelector('#vertexModeBtn');if(v){v.dataset.meshMode='vertex';v.textContent='Vértice';v.title='Seleção de vértices · 1'}
  const controls=document.createElement('div');controls.className='mesh-tool-controls';controls.innerHTML=`<label>Valor <input id="meshOpValue" type="number" value="0.20" step="0.05"></label><label>Segmentos <input id="bevelSegments" type="number" value="2" min="1" max="6"></label><label>Raio prop. <input id="propRadius" type="number" value="0.75" min="0.01" step="0.05"></label><select id="mergeMode"><option value="center">Merge no centro</option><option value="first">Primeiro vértice</option><option value="last">Último vértice</option><option value="distance">Weld por distância</option></select><label>Subdivisão <input id="subdivisionLevel" type="number" min="1" max="3" value="1"></label><div class="button-row"><button id="subdivisionPreviewBtn" title="Preview não destrutivo">Preview Subdivision</button><button id="subdivisionApplyBtn" title="Aplicar preview">Aplicar Subdivision</button></div>`;sec.appendChild(controls);
  sec.querySelectorAll('[data-mesh-mode]').forEach(b=>b.addEventListener('click',()=>this.active&&this.setMode(b.dataset.meshMode)));
  const value=()=>Number(document.querySelector('#meshOpValue')?.value)||.2;
  document.querySelector('#extrudeMeshBtn')?.addEventListener('click',()=>this.extrude(value()));
  document.querySelector('#insetMeshBtn')?.addEventListener('click',()=>this.inset(value()));
  document.querySelector('#bevelMeshBtn')?.addEventListener('click',()=>this.bevel(value(),Number(document.querySelector('#bevelSegments')?.value)||1));
  document.querySelector('#loopCutMeshBtn')?.addEventListener('click',()=>this.loopCut(Math.max(.05,Math.min(.95,value()))));
  document.querySelector('#knifeMeshBtn')?.addEventListener('click',()=>this.beginKnife());
  document.querySelector('#propEditBtn')?.addEventListener('click',e=>{this.setProportional(!this.proportional,Number(document.querySelector('#propRadius')?.value)||.75);e.currentTarget.classList.toggle('active',this.proportional)});
  document.querySelector('#subdivisionPreviewBtn')?.addEventListener('click',e=>{const level=Number(document.querySelector('#subdivisionLevel')?.value)||1;this.toggleSubdivisionPreview(level);e.currentTarget.classList.toggle('active',this.subdivision.enabled(this.mesh))});
  document.querySelector('#subdivisionApplyBtn')?.addEventListener('click',()=>this.applySubdivisionPreview());
  this.engine.renderer?.domElement?.addEventListener('pointermove',e=>this._knifeMove(e));
  document.addEventListener('keydown',e=>{if(!this.active||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const k=e.key.toLowerCase();if(e.key==='1')this.setMode('vertex');if(e.key==='2')this.setMode('edge');if(e.key==='3')this.setMode('face');if(k==='e'&&this.mode==='face'){e.preventDefault();this.extrude(value())}if(k==='i'&&this.mode==='face'){e.preventDefault();this.inset(value())}if(k==='b'&&this.mode==='edge'){e.preventDefault();this.bevel(value(),Number(document.querySelector('#bevelSegments')?.value)||1)}if(k==='k'){e.preventDefault();this.beginKnife()}if(k==='o'){this.setProportional(!this.proportional,Number(document.querySelector('#propRadius')?.value)||.75);document.querySelector('#propEditBtn')?.classList.toggle('active',this.proportional)}if(e.ctrlKey&&k==='r'){e.preventDefault();this.loopCut(.5)}if(e.key==='Escape')this.cancelKnife()});
 }
 enter(object){let mesh=object?.isMesh?object:null;if(!mesh)object?.traverse(o=>{if(!mesh&&o.isMesh&&!o.userData?.helper)mesh=o});if(!mesh||!mesh.geometry?.getAttribute('position'))return false;this.exit();mesh.geometry=editableGeometry(mesh.geometry);this.mesh=mesh;this.selection.enter(mesh);this.proxy=new THREE.Object3D();this.proxy.userData.helper=true;this.engine.scene.add(this.proxy);this.engine.detach();this.engine.setTransformMode('translate');this.engine.attach(this.proxy);this.engine.transform.visible=false;this._syncModeStatus();return true}
 exit(){this.cancelKnife();if(this.mesh&&this.subdivision.enabled(this.mesh))this.subdivision.disable(this.mesh,{restore:true});this.selection.exit();if(this.proxy){this.engine.detach();this.proxy.parent?.remove(this.proxy)}this.mesh=null;this.proxy=null;this.dragBefore=null;this._syncModeStatus()}
 setMode(mode){if(!this.active)return;this.cancelKnife();this.selection.setMode(mode);document.querySelectorAll('[data-mesh-mode]').forEach(b=>b.classList.toggle('active',b.dataset.meshMode===mode));this._updateProxy();this._syncModeStatus()}
 pointerSelect(e){if(this.knifeState)return this._knifeClick(e);return this.selection.pointerSelect(e)}
 clearSelection(){this.selection.clear()}
 transformStart(){if(!this.active||!this.selected.size)return;if(this.subdivision.enabled(this.mesh))this.subdivision.disable(this.mesh,{restore:true});this.dragBefore=this.mesh.geometry.clone();this.proxyStart=this.proxy.position.clone()}
 transformChange(){if(!this.active||!this.selected.size||!this.proxyStart)return;const deltaWorld=this.proxy.position.clone().sub(this.proxyStart);if(deltaWorld.lengthSq()<1e-16)return;const p=this.mesh.geometry.getAttribute('position'),selected=[...this.selected],all=new Set(selected);if(this.proportional){const centers=selected.map(i=>new THREE.Vector3().fromBufferAttribute(p,i));for(let i=0;i<p.count;i++){if(all.has(i))continue;const v=new THREE.Vector3().fromBufferAttribute(p,i);let d=Infinity;for(const c of centers)d=Math.min(d,v.distanceTo(c));if(d<this.proportionalRadius)all.add(i)}}for(const i of all){const local=new THREE.Vector3().fromBufferAttribute(p,i),world=this.mesh.localToWorld(local.clone()),weight=this.proportional&&!this.selected.has(i)?this._weight(local,p,selected):1;world.addScaledVector(deltaWorld,weight);const next=this.mesh.worldToLocal(world);applyClip(next,this.getMirror());p.setXYZ(i,next.x,next.y,next.z)}p.needsUpdate=true;refreshGeometry(this.mesh.geometry);this.selection.rebuild();this.proxyStart.copy(this.proxy.position)}
 _weight(v,p,ids){let d=Infinity;for(const i of ids)d=Math.min(d,v.distanceTo(new THREE.Vector3().fromBufferAttribute(p,i)));const t=Math.max(0,1-d/this.proportionalRadius);return t*t*(3-2*t)}
 transformEnd(){if(!this.dragBefore)return;const before=this.dragBefore,after=this.mesh.geometry.clone();this.dragBefore=null;this.onCommit(before,after,this.mesh,true,'Transform Mesh');this._updateProxy()}
 snapshot(){return this.mesh?.geometry?.clone()||null}
 restore(g){if(!this.mesh||!g)return;this.mesh.geometry.dispose?.();this.mesh.geometry=g.clone();refreshGeometry(this.mesh.geometry);this.selection.enter(this.mesh);this._updateProxy()}
 mergeSelected(mode=null,threshold=null){if(!this.active||this.selected.size<2)return false;mode=mode||document.querySelector('#mergeMode')?.value||'center';threshold=threshold??Math.abs(Number(document.querySelector('#meshOpValue')?.value)||.0001);const before=this.mesh.geometry.clone(),p=this.mesh.geometry.getAttribute('position'),ids=[...this.selected],target=new THREE.Vector3();if(mode==='first')target.fromBufferAttribute(p,ids[0]);else if(mode==='last')target.fromBufferAttribute(p,ids[ids.length-1]);else{for(const i of ids)target.add(new THREE.Vector3().fromBufferAttribute(p,i));target.multiplyScalar(1/ids.length)}applyClip(target,this.getMirror());if(mode==='distance'){for(let a=0;a<ids.length;a++){const va=new THREE.Vector3().fromBufferAttribute(p,ids[a]);for(let b=a+1;b<ids.length;b++){const vb=new THREE.Vector3().fromBufferAttribute(p,ids[b]);if(va.distanceTo(vb)<=threshold)p.setXYZ(ids[b],va.x,va.y,va.z)}}}else for(const i of ids)p.setXYZ(i,target.x,target.y,target.z);p.needsUpdate=true;refreshGeometry(this.mesh.geometry);this.selection.rebuild();this.onCommit(before,this.mesh.geometry.clone(),this.mesh,true,mode==='distance'?'Weld':'Merge');return true}
 extrude(distance=.2){const faces=this.selection.selectedFaceIndices();if(!faces.size)return false;return this._apply(extrudeFaces(this.mesh.geometry,faces,distance),'Extrude')}
 inset(amount=.2){const faces=this.selection.selectedFaceIndices();if(!faces.size)return false;return this._apply(insetFaces(this.mesh.geometry,faces,amount),'Inset')}
 loopCut(position=.5){const edges=this.mode==='edge'?this.selection.edges:null;return this._apply(loopCut(this.mesh.geometry,position,edges),'Loop Cut')}
 bevel(width=.08,segments=2){if(this.mode!=='edge'||!this.selection.edges.size)return false;return this._apply(bevelEdges(this.mesh.geometry,this.selection.edges,width,segments),'Bevel')}
 beginKnife(){if(!this.active){return false}this.setMode('face');this.knifeState={face:null,start:null};this._setKnifePreview(null,null);const s=document.querySelector('#selectionStatus');if(s)s.textContent='Knife: clique em uma aresta da face e depois em outra';return true}
 _knifeClick(e){const ray=this.engine.screenRay(e.clientX,e.clientY),hit=ray.intersectObject(this.mesh,false)[0];if(hit?.faceIndex==null)return true;const local=hit.point.clone();this.mesh.worldToLocal(local);const snapped=nearestPointOnFaceEdges(this.mesh.geometry,hit.faceIndex,local);if(!this.knifeState.start){this.knifeState={face:hit.faceIndex,start:snapped};this._setKnifePreview(snapped,snapped);return true}if(hit.faceIndex!==this.knifeState.face){this.knifeState={face:hit.faceIndex,start:snapped};this._setKnifePreview(snapped,snapped);return true}const next=knifeFace(this.mesh.geometry,hit.faceIndex,this.knifeState.start,snapped);this.cancelKnife();return this._apply(next,'Knife')}
 _knifeMove(e){if(!this.active||!this.knifeState?.start)return;const ray=this.engine.screenRay(e.clientX,e.clientY),hit=ray.intersectObject(this.mesh,false)[0];if(hit?.faceIndex!==this.knifeState.face)return;const local=hit.point.clone();this.mesh.worldToLocal(local);const q=nearestPointOnFaceEdges(this.mesh.geometry,hit.faceIndex,local);this._setKnifePreview(this.knifeState.start,q)}
 _setKnifePreview(a,b){if(this.knifePreview){this.knifePreview.parent?.remove(this.knifePreview);this.knifePreview.geometry.dispose();this.knifePreview.material.dispose();this.knifePreview=null}if(!a||!b||!this.mesh)return;const g=new THREE.BufferGeometry().setFromPoints([a,b]);const m=new THREE.LineBasicMaterial({color:0xffd166,depthTest:false});this.knifePreview=new THREE.Line(g,m);this.knifePreview.userData.helper=true;this.knifePreview.renderOrder=1200;this.mesh.add(this.knifePreview)}
 cancelKnife(){this.knifeState=null;this._setKnifePreview(null,null)}
 subdivide(level=1){if(!this.active)return false;let next=this.mesh.geometry.clone();for(let i=0;i<Math.max(1,Math.min(3,level));i++){const tri=next.getAttribute('position').count/3;if(tri*4>200000){alert('Subdivisão cancelada: limite de 200 mil triângulos.');return false}next=subdivisionOnce(next)}return this._apply(next,'Subdivision')}
 toggleSubdivisionPreview(level=1){if(!this.active)return false;if(this.subdivision.enabled(this.mesh)){this.subdivision.disable(this.mesh,{restore:true});this.selection.enter(this.mesh);return false}this.subdivision.enable(this.mesh,level);this.selection.enter(this.mesh);return true}
 applySubdivisionPreview(){if(!this.active||!this.subdivision.enabled(this.mesh))return false;const preview=this.mesh.geometry.clone(),base=this.subdivision.base(this.mesh)?.clone();this.subdivision.apply(this.mesh);this.selection.enter(this.mesh);if(base)this.onCommit(base,preview.clone(),this.mesh,true,'Apply Subdivision');return true}
 setProportional(enabled,radius=this.proportionalRadius){this.proportional=!!enabled;this.proportionalRadius=Math.max(.01,Number(radius)||.75)}
 _apply(next,label){if(!next||!this.mesh)return false;if(this.subdivision.enabled(this.mesh))this.subdivision.disable(this.mesh,{restore:true});const before=this.mesh.geometry.clone();this.mesh.geometry.dispose?.();this.mesh.geometry=next;refreshGeometry(next);this.selection.enter(this.mesh);this.mesh.userData.lastMeshOperation=label;this.onCommit(before,next.clone(),this.mesh,true,label);return true}
 _updateProxy(){if(!this.proxy||!this.mesh||!this.selected.size){if(this.engine.transform)this.engine.transform.visible=false;return}const p=this.mesh.geometry.getAttribute('position'),sum=new THREE.Vector3();for(const i of this.selected){const v=new THREE.Vector3().fromBufferAttribute(p,i);this.mesh.localToWorld(v);sum.add(v)}sum.multiplyScalar(1/this.selected.size);this.proxy.position.copy(sum);this.proxy.quaternion.identity();this.proxy.scale.set(1,1,1);this.proxyStart=sum.clone();this.engine.attach(this.proxy);this.engine.transform.visible=true}
 _syncModeStatus(s){const status=document.querySelector('#modeStatus');if(!status)return;if(!this.active){status.textContent='MODO OBJETO';return}const labels={vertex:'VÉRTICE',edge:'ARESTA',face:'FACE'};status.textContent=`MODO ${labels[this.mode]||'MALHA'}`;const selectionStatus=document.querySelector('#selectionStatus');if(selectionStatus&&s)selectionStatus.textContent=`${s.count} ${labels[s.mode]?.toLowerCase()||'elemento'}${s.count===1?'':'s'} selecionado${s.count===1?'':'s'}`}
}
function applyClip(v,{axes=[],clipping=false}={}){if(!clipping)return;for(const a of axes||[])if(Math.abs(v[a])<.045)v[a]=0}
