import * as THREE from 'three';

export class MeshEditor{
 constructor(engine,{onCommit=()=>{},getMirror=()=>({axes:[],clipping:false}),onSelectionChange=()=>{}}={}){this.engine=engine;this.onCommit=onCommit;this.getMirror=getMirror;this.onSelectionChange=onSelectionChange;this.mesh=null;this.points=null;this.proxy=null;this.selected=new Set();this.dragBefore=null;this.proxyStart=null;this.linkTolerance=1e-5}
 get active(){return!!this.mesh}
 enter(object){let mesh=object?.isMesh?object:null;if(!mesh)object?.traverse(o=>{if(!mesh&&o.isMesh&&!o.userData?.helper)mesh=o});if(!mesh||!mesh.geometry?.getAttribute('position'))return false;this.exit();this.mesh=mesh;this.points=new THREE.Points(mesh.geometry.clone(),new THREE.PointsMaterial({color:0xc4b5fd,size:.065,sizeAttenuation:true,depthTest:false,transparent:true,opacity:.96}));this.points.name='_VertexPoints';this.points.renderOrder=999;this.points.userData.helper=true;mesh.add(this.points);this.proxy=new THREE.Object3D();this.proxy.name='_VertexProxy';this.proxy.userData.helper=true;this.engine.scene.add(this.proxy);this.engine.detach();this.engine.setTransformMode('translate');this.engine.attach(this.proxy);this.engine.transform.visible=false;this._syncPoints();this._emitSelection();return true}
 exit(){if(this.points){this.points.parent?.remove(this.points);this.points.geometry.dispose();this.points.material.dispose()}if(this.proxy){this.engine.detach();this.proxy.parent?.remove(this.proxy)}this.mesh=null;this.points=null;this.proxy=null;this.selected.clear();this.dragBefore=null;this._emitSelection()}
 pointerSelect(e){if(!this.active)return false;const ray=this.engine.screenRay(e.clientX,e.clientY);ray.params.Points.threshold=.14;const hit=ray.intersectObject(this.points,false)[0];if(!hit){if(!e.shiftKey)this.clearSelection();return true}const linked=this._linkedIndices(hit.index);if(e.shiftKey){const allSelected=linked.every(i=>this.selected.has(i));for(const i of linked)allSelected?this.selected.delete(i):this.selected.add(i)}else{this.selected.clear();linked.forEach(i=>this.selected.add(i))}this._updateProxy();this._emitSelection();return true}
 clearSelection(){this.selected.clear();if(this.proxy)this.engine.transform.visible=false;this._emitSelection()}
 _linkedIndices(seed){const p=this.mesh?.geometry?.getAttribute('position');if(!p||seed==null)return[];const x=p.getX(seed),y=p.getY(seed),z=p.getZ(seed),eps=this.linkTolerance,out=[];for(let i=0;i<p.count;i++){if(Math.abs(p.getX(i)-x)<=eps&&Math.abs(p.getY(i)-y)<=eps&&Math.abs(p.getZ(i)-z)<=eps)out.push(i)}return out.length?out:[seed]}
 _syncPoints(){if(!this.points||!this.mesh)return;const src=this.mesh.geometry.getAttribute('position'),dst=this.points.geometry.getAttribute('position');if(!dst||dst.count!==src.count){this.points.geometry.dispose();this.points.geometry=this.mesh.geometry.clone()}else{dst.array.set(src.array);dst.needsUpdate=true}this.points.geometry.computeBoundingSphere?.()}
 _updateProxy(){if(!this.proxy||!this.mesh||!this.selected.size){if(this.engine.transform)this.engine.transform.visible=false;return}const p=this.mesh.geometry.getAttribute('position'),sum=new THREE.Vector3();for(const i of this.selected){const v=new THREE.Vector3().fromBufferAttribute(p,i);this.mesh.localToWorld(v);sum.add(v)}sum.multiplyScalar(1/this.selected.size);this.proxy.position.copy(sum);this.proxy.quaternion.identity();this.proxy.scale.set(1,1,1);this.proxyStart=sum.clone();this.engine.attach(this.proxy);this.engine.transform.visible=true}
 _emitSelection(){this.onSelectionChange({count:this.selected.size,active:this.active})}
 transformStart(){if(!this.active||!this.selected.size)return;this.dragBefore=this.snapshot();this.proxyStart=this.proxy.position.clone()}
 transformChange(){if(!this.active||!this.selected.size||!this.proxyStart)return;const delta=this.proxy.position.clone().sub(this.proxyStart);if(delta.lengthSq()<1e-16)return;const pos=this.mesh.geometry.getAttribute('position');for(const i of this.selected){const local=new THREE.Vector3().fromBufferAttribute(pos,i),world=this.mesh.localToWorld(local.clone()).add(delta),next=this.mesh.worldToLocal(world);applyClip(next,this.getMirror());pos.setXYZ(i,next.x,next.y,next.z)}pos.needsUpdate=true;this.mesh.geometry.computeVertexNormals?.();this.mesh.geometry.computeBoundingBox?.();this.mesh.geometry.computeBoundingSphere?.();this.proxyStart.copy(this.proxy.position);this._syncPoints()}
 transformEnd(){if(!this.active||!this.dragBefore)return;const before=this.dragBefore,after=this.snapshot();this.dragBefore=null;this.onCommit(before,after,this.mesh);this._updateProxy()}
 snapshot(){const p=this.mesh?.geometry?.getAttribute('position');return p?new Float32Array(p.array):null}
 restore(array){if(!this.mesh||!array)return;const p=this.mesh.geometry.getAttribute('position');if(p.array.length!==array.length)return;p.array.set(array);p.needsUpdate=true;this.mesh.geometry.computeVertexNormals?.();this.mesh.geometry.computeBoundingBox?.();this.mesh.geometry.computeBoundingSphere?.();this._syncPoints();this._updateProxy()}
 mergeSelected(){if(!this.active||this.selected.size<2)return false;const before=this.snapshot(),p=this.mesh.geometry.getAttribute('position'),avg=new THREE.Vector3();for(const i of this.selected)avg.add(new THREE.Vector3().fromBufferAttribute(p,i));avg.multiplyScalar(1/this.selected.size);applyClip(avg,this.getMirror());for(const i of this.selected)p.setXYZ(i,avg.x,avg.y,avg.z);p.needsUpdate=true;this.mesh.geometry.computeVertexNormals?.();this.mesh.geometry.computeBoundingBox?.();this.mesh.geometry.computeBoundingSphere?.();this._syncPoints();this._updateProxy();this.onCommit(before,this.snapshot(),this.mesh);return true}
 subdivide(){
  if(!this.active)return false;const old=this.mesh.geometry,non=old.index?old.toNonIndexed():old.clone(),pos=non.getAttribute('position');if(!pos||pos.count<3)return false;const triangles=pos.count/3;if(triangles*4>200000){alert('Para proteger o navegador, esta subdivisão passaria de 200 mil triângulos. Reduza o modelo antes de continuar.');non.dispose();return false}
  const next=subdivideTriangleGeometry(non);const before=old.clone();this.mesh.geometry=next;non.dispose();this.points.geometry.dispose();this.points.geometry=next.clone();this.selected.clear();this.engine.transform.visible=false;this._emitSelection();this.onCommit(before,next.clone(),this.mesh,true);return true
 }
}

function subdivideTriangleGeometry(source){
 const out=new THREE.BufferGeometry(),names=Object.keys(source.attributes).filter(n=>n!=='normal'),pos=source.getAttribute('position'),triangles=pos.count/3;
 for(const name of names){const a=source.getAttribute(name),arr=[];for(let t=0;t<triangles;t++){const i=t*3,A=read(a,i),B=read(a,i+1),C=read(a,i+2),AB=mid(A,B),BC=mid(B,C),CA=mid(C,A);for(const tri of [[A,AB,CA],[AB,B,BC],[CA,BC,C],[AB,BC,CA]])for(const v of tri)arr.push(...v)}const Ctor=a.array.constructor,typed=new Ctor(arr);out.setAttribute(name,new THREE.BufferAttribute(typed,a.itemSize,a.normalized))}
 out.computeVertexNormals();out.computeBoundingBox();out.computeBoundingSphere();return out
}
function read(attr,index){const out=[];for(let c=0;c<attr.itemSize;c++)out.push(attr.array[index*attr.itemSize+c]);return out}
function mid(a,b){return a.map((v,i)=>(v+b[i])*.5)}
function applyClip(v,{axes=[],clipping=false}={}){if(!clipping)return;for(const a of axes||[])if(Math.abs(v[a])<.045)v[a]=0}
